env:
    MANIFEST: https://github.com/ExodusOS/android.git
    MANIFEST_BRANCH: lineage-19.1
    LOCAL_MANIFEST: https://github.com/angel-1999-stack/local_manifest.git
    LOCALMANIFEST_BRANCH : los19.1
    DEVICE: onclite
    OEM: xiaomi
    LUNCH_COMBO: lineage_onclite-userdebug
    TARGET: bacon
    OUTPUT: ExodusOS*.zip

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
