env:
    MANIFEST: https://github.com/LineageOS/android.git
    MANIFEST_BRANCH: lineage-20.0
    LOCAL_MANIFEST: https://github.com/xack21/local_manifest.git
    LOCALMANIFEST_BRANCH : main
    DEVICE: fog
    OEM: xiaomi
    LUNCH_COMBO: lineage_fog-userdebug
    TARGET: bacon
    OUTPUT: *.zip

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  timeout_in: 240m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
