env:
    MANIFEST: https://github.com/The-RAVEN-OS/manifest.git
    MANIFEST_BRANCH: twelve
    DEVICE: A6020
    OEM: lenovo
    DT_LINK: https://github.com/Sushrut1101-ROMs/device_lenovo_A6020.git -b rr_10
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/hsj51/vendor_lenovo_A6020.git -b 10.x
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/jro1979oliver/android_kernel_lenovo_msm8916.git
    PLATFORM: msm8916
    KT_PATH: kernel/$OEM/$PLATFORM
    EXTRA_CMD: "git clone --depth=1 https://github.com/ghostrider-reborn/prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-6.x.git $SYNC_PATH/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-6.x"
    LUNCH_COMBO: rr_A6020-userdebug
    TARGET: bacon
    OUTPUT: RROS*.zip

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  timeout_in: 240m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 16
      memory: 128G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh

