env:
    MANIFEST: https://github.com/ArrowOS/android_manifest.git
    MANIFEST_BRANCH: arrow-12.1
    LOCAL_MANIFEST: https://github.com/adarsh956/local_manifest.git
    LOCALMANIFEST_BRANCH : main
    DEVICE: garden
    OEM: xiaomi
    LUNCH_COMBO: arrow_garden-userdebug
    TARGET: bacon
    OUTPUT: Arrow*.zip

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRCLE_SHELL: bash

task:
  name: "AOSP Build"
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
